from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
	url(r'^$', 'entrust_app.views.home'),
	url(r'^post-task/$','entrust_app.views.post_task'),
	url(r'^home/$','entrust_app.views.homepage'),
	url(r'^resources/$','entrust_app.views.resources'),
	url(r'search/$','entrust_app.views.search'),
	url(r'^entrust-task$','entrust_app.views.task_entrust'),
	url(r'^update/$','entrust_app.views.update'),
	url(r'^accept_list/$','entrust_app.views.accept_list'),
	url(r'^accept-task/(?P<task_id>\d+)$','entrust_app.views.task_accept', name='task_accept'),
	url(r'^signup$','entrust_app.views.signup'),
	url(r'^discuss-task/(?P<discussion_id>\d+)$','entrust_app.views.task_discussion', name='task_discussion'),
	url(r'^approve-task/(?P<discussion_id>\d+)$','entrust_app.views.task_approved', name='task_approved'),
	url(r'^complete-task/(?P<discussion_id>\d+)$','entrust_app.views.task_completed', name='task_completed'),
	url(r'^delete-task/(?P<task_id>\d+)$','entrust_app.views.task_deleted', name='task_deleted'),
	url(r'^refresh-task/$','entrust_app.views.task_refresh', name='task_refresh'),
	url(r'^login$','entrust_app.views.loginuser'),
	url(r'^viewtasks$','entrust_app.views.viewtasks'),
	url(r'^testimonial/(?P<req_user>\w+)/$','entrust_app.views.view_testimonials', name='view_testimonials'),
	url(r'^testimonial$','entrust_app.views.testimonial', name='testimonial'),
	url(r'^logout$','entrust_app.views.logout_view'),
	url(r'^photo/(?P<u_name>\w+)/$', 'entrust_app.views.get_photo', name='profile_pic'),
	url(r'^change$','entrust_app.views.editprofile', name = 'edit_profile'),
	url(r'^task-queued/(?P<task_id>\d+)/$','entrust_app.views.task_queue', name = 'task_queue'),
	url(r'^show-queue/(?P<task_id>\d+)/$','entrust_app.views.show_queue', name = 'show_queue'),
	url(r'^profile/(?P<u_name>\w+)/$','entrust_app.views.viewprofile', name='display_profile'),
	url(r'^confirm-registration/(?P<username>[a-zA-Z0-9_@\+\-]+)/(?P<token>[a-z0-9\-]+)$', 'entrust_app.views.confirmemail', name='confirm'),
	url(r'^resetpassword/passwordsent/$', 'entrust_app.views.password_reset_done', name='password_reset_done'),
	url(r'^resetpassword/$', 'entrust_app.views.password_reset', name='password_reset'),
	url(r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'entrust_app.views.password_reset_confirm'),
	url(r'^reset/done/$', 'entrust_app.views.password_reset_complete'),
	url(r'^accounts/password_change/$','entrust_app.views.password_change'),
	url(r'^accounts/password_change/done/$', 'entrust_app.views.password_change_done'),
)
